animal_words = ["Cat", "Cattle", "Dog", "Donkey", "Goat", "Horse", 
	"Pig", "Rabbit", "Chicken", "Duck", "Goose", "Pigeon", "Turkey", 
	"Aardvark", "buffalo", "elephant", "leopard", "Albatross", 
	"Alligator", "Alpaca", "bison", "robin", "Amphibian", 
	"Anaconda", "Angelfish", "Anglerfish", "Ant", "Anteater", 
	"Antelope", "Antlion", "Ape", "Aphid", "leopard", "Fox", "Wolf", 
	"Armadillo", "crab", "donkey", "Baboon", "Badger", "eagle", 
	"Barnacle", "Barracuda", "Basilisk", "Bass", "Bat", "whale", 
	"Bear", "Beaver", "Bedbug", "Bee", "Beetle", "Bird", "Bison", 
	"Blackbird", "panther", "spider", "Boa", "Boar", "Bobcat", 
	"Bobolink", "Bonobo", "Booby", "jellyfish", "Bovid", "Bug", 
	"Butterfly", "Buzzard", "Camel", "Canid", "buffalo", "Capybara", 
	"Cardinal", "Caribou", "Carp", "Cat", "Catshark", "Caterpillar", 
	"Catfish", "Cattle", "Centipede", "Cephalopod", "Chameleon", 
	"Cheetah", "Chickadee", "Chicken", "Chimpanzee", "Chinchilla", 
	"Chipmunk", "Clam", "Clownfish", "Cobra", "Cockroach", "Cod", 
	"Condor", "Constrictor", "Coral", "Cougar", "Cow", "Coyote", 
	"Crab", "Crane", "fly", "Crawdad", "Crayfish", "Cricket", 
	"Crocodile", "Crow", "Cuckoo", "Cicada", "Damselfly", "Deer", 
	"Dingo", "Dinosaur", "Dog", "Dolphin", "Donkey", "Dormouse", 
	"Dove", "Dragonfly", "Dragon", "Duck", "beetle", "Eagle", 
	"Earthworm", "Earwig", "Echidna", "Eel", "Egret", "Elephant", 
	"seal", "Elk", "Emu", "Ermine", "Falcon", "Ferret", "Finch", 
	"Firefly", "Fish", "Flamingo", "Flea", "Fly", "Flyingfish", 
	"Fowl", "Fox", "Frog", "bat", "Gamefowl", "Galliform", "Gazelle", 
	"Gecko", "Gerbil", "panda", "squid", "Gibbon", "Giraffe", "Goat", 
	"Goldfish", "Goose", "Gopher", "Gorilla", "Grasshopper", "heron", 
	"shark", "bear", "sloth", "Grouse", "Gull", "Guppy", "Haddock", 
	"Halibut", "Hamster", "Hare", "Harrier", "Hawk", "Hedgehog", "crab", 
	"Heron", "Herring", "Hippopotamus", "Hookworm", "Hornet", "Horse", 
	"Hoverfly", "Hummingbird", "Hyena", "Iguana", "Impala", "Jackal", 
	"Jaguar", "Jay", "Jellyfish", "Junglefowl", "Kangaroo", "Kingfisher", 
	"Kite", "Kiwi", "Koala", "Koi", "Krill", "Ladybug", "Lamprey", 
	"Landfowl", "snail", "Lark", "Leech", "Lemming", "Lemur", "Leopard", 
	"Leopon", "Limpet", "Lion", "Lizard", "Llama", "Lobster", "Locust", 
	"Loon", "Louse", "Lungfish", "Lynx", "Macaw", "Mackerel", "Magpie", 
	"Mammal", "Manatee", "Mandrill", "Marlin", "Marmoset", "Marmot", 
	"Meadowlark", "Meerkat", "Mink", "Minnow", "Mite", "Mockingbird", 
	"Mole", "Mollusk", "Mongoose", "lizard", "Monkey", "Moose", 
	"Mosquito", "Moth", "goat", "Mouse", "Mule", "Muskox", "Narwhal", 
	"Newt", "quail", "Nightingale", "Ocelot", "Octopus", "Opossum", 
	"Orangutan", "Orca", "Ostrich", "Otter", "Owl", "Ox", "Panda", 
	"Panther", "Parakeet", "Parrot", "Parrotfish", "Partridge", "Peacock", 
	"Peafowl", "Pelican", "Penguin", "Perch", "falcon", "Pheasant", "Pig", 
	"Pigeon", "Pike", "Pinniped", "Piranha", "Planarian", "Platypus", 
	"Pony", "Porcupine", "Porpoise", "Possum", "Prawn", "Primate", 
	"Ptarmigan", "Puffin", "Puma", "Python", "Quail", "Quelea", "Quokka", 
	"Rabbit", "Raccoon", "trout", "Rat", "Rattlesnake", "Raven", "Reindeer", 
	"Reptile", "Rhinoceros", "Roadrunner", "Rodent", "Rook", "Rooster", 
	"Roundworm", "Sailfish", "Salamander", "Salmon", "Sawfish", "Scallop", 
	"Scorpion", "Seahorse", "Shark", "Sheep", "Shrew", "Shrimp", "Silkworm", 
	"Silverfish", "Skink", "Skunk", "Sloth", "Slug", "Smelt", "Snail", "Snake", 
	"Snipe", "Sole", "Sparrow", "Spider", "Spoonbill", "Squid", "Squirrel", 
	"Starfish", "mole", "trout", "Stingray", "Stoat", "Stork", "Sturgeon", 
	"glider", "Swallow", "Swan", "Swift", "Swordfish", "Swordtail", "Tarantula",
	"Termite", "Thrush", "Tick", "Tiger", "Toad", "Tortoise", "Toucan", "spider", 
	"frog", "Trout", "Tuna", "Turkey", "Turtle", "bat", "squid", "Viper", "Vole", 
	"Vulture", "Wallaby", "Walrus", "Wasp", "Warbler", "Boa", "buffalo", "Weasel", 
	"Whale", "Whitefish", "crane", "Wildcat", "Wolf", "Wombat", "Woodpecker", "Worm", "Wren", "Yak", "Zebra", "Alpaca", "Cat", "Cattle", "Chicken", "Dog", "canary", "camel", "duck", "goat", "goose", "hedgehog", "pig", "pigeon", "rabbit", "fox", "turkey", "Donkey", "mouse", "rat", "Ferret", "Goldfish", "pig", "Guppy", "Horse", "Llama", "dove", "Sheep", "fish", "finch", "Yak", "buffalo", ]
harry_potter_words = ["wand", "ollivander", "dragon", "toad", 
	"harry", "potter", "ronald", "weasley", "hermione", "granger", 
	"hogwarts", "hogsmeade", "witchcraft", "muggle", "wizardry", 
	"wizard", "voldemort", "albus", "dumbledore", "scar", "hagrid", 
	"slytherin", "hufflepuff", "gryffindor", "ravenclaw", "neville", 
	"longbottom", "butterbeer", "horcrux", "spells", "potion", 
	"magic", "owl"]
vegetable_words = ["Arugula", "Broccoli", "Cabbage", "Celery", "pumpkin", "Kale", "Komatsuna", "Kuka", "lettuce", "spinach", "Melokhia", "cabbage", "Orache", "Peabeet", "kale", "Asparagus", "Chives", "garlic", "fennel", "Leek", "Onion", "asparagus", "Scallion", "Shallot", "Beetroot", "Carrot", "Cassava", "yam", "artichoke", "Parsnip", "Potato", "turnip", "Radish", "Turnip", "Yam"]
winter_words = ["snow", "skate", "ski", "snowboard", "snowshoe", "pole", "cold", "sledding", "snowpants"]



